import WebBuilder from "../index.js";
let webBuilder = WebBuilder.build();
webBuilder.build_fonts();
webBuilder.build_images();
webBuilder.build_styleLib();
webBuilder.build_scriptLib();
webBuilder.build_sass();
webBuilder.build_ts();
webBuilder.build_copy();
webBuilder.start();